### PR TITLE
Split configure into two functions and add Check Config button

### PR DESCRIPTION
**Pull request by exciton**
Add support to read back protection reports and check against config
Blank out setting associations, since it breaks communication with the
hub (at least C7)

### CODE REVIEW

**Comment by exciton** [comment]
Apologies for the whitespace changes. Editor deletes trailing whitespace automatically.

**Comment by muchu999** [comment]
Hi, by commenting out the multichannel associations code, the periodic reports will not work anymore. If you know yourself, I would like to know why is the existing code not working? "Breaks communication" Is it because of lost messages?

**Comment by exciton** [comment]
Yes - the NotificationReports from alarm inputs changing don't come through with the changes to associations.
What's the easiest way to test out periodic reports? I'm not using them, but I can try to find a combination that works for both.

**Comment by muchu999** [comment]
You can enable automatic reports using these values:

Analog inputs - periodical reports: 60
Internal temperature sensor - periodical reports: 60
External sensors - periodical reports: 60
Analog inputs - minimal change to report:: 1
Internal temperature sensor - minimal change to report: 1
External sensors - minimal change to report: 1

The problem is that IF the problem is due to lost messages/overrun, what works for you might not work for others. I received a couple of other symptoms of this from other users and they were not all showing the same thing so I assume different messages were getting lost in their cases.

I changed the version of "multiChannelAssociationV2" to "multiChannelAssociationV3" in the code. V3 was not supported by Hubitat when the driver was initially written... but V3 is what the implant officially supports.

I made a few more changes on top of yours and will post the file on a github branch probably today.

**Comment by exciton** [comment]
Ok I'll test it out. I'm my case I was getting no messages at all (not an
issue of network congestion), so should be easy to debug.

**Comment by muchu999** [comment]
OK, I put a new version here: 

https://github.com/muchu999/Hubitat/tree/C7-test/Fibaro%20FBGS-222%20Smart%20Implant

I re-enabled the association commands so it might not work on your system at first, but who knows. I like looking at logs if you can post them...

**Comment by exciton** [comment]
Running configure on the stock driver gives this:
image

Switching to this driver and running checkConfig associations look like this:
image

Full config like this:
image

Looks like periodic reports come in:
image

I get reports from sensors triggering as expected:
image

Running reconfigure with the C7-test branch:
image

I get no periodic reports, and don't get triggered reports from sensors changing (only reports when outputs are changed via zwave)

Changing the groupingIdentifier 1 endpoint to 0 gets periodic reports back again:
cmds << zwave.multiChannelAssociationV3.multiChannelAssociationSet(groupingIdentifier: 1, nodeId: [0,1,0]) 
image

I'm not sure what (if anything) is coming through from groupingIdentifier 2 and 3, but setting the endpoint to 0 on groupingIdentifier 1 seems to be important to getting the periodic reports and the triggered reports.

**Comment by muchu999** [comment]
Yea, I saw your post on Hubitat, didn't see it before this afternoon. I updated the code in the same branch to reflect the associations of the stock driver. Group 2 and 3 were set that way when I was testing advanced features but nobody uses it. I will leave the delays in for now. I think it is safe to merge that to the main branch?

**Comment by exciton** [comment]
Yeah that looks good!

**Pull request closed without merging**
